#!/usr/bin/env python3
"""Write one dataset config per fragments file: one ChromBPNet dataset per library.

Each ``<stem>.fragments.tsv.gz`` under --fragments-dir becomes dataset
``<prefix><stem>`` with its config at ``<configs-dir>/<dataset>/config.yaml``,
used through ``DATASET_CONFIG``. Paths are absolute, so a config means the same
thing whatever the environment. Peaks are called by 00.0.call_peaks into
``<dataset-root>/peaks/<dataset>/``; everything ChromBPNet writes goes under
``<dataset-root>/chrombpnet/<dataset>/``.

The Tn5 shift is pinned per file from detect_shifts.py's output (--shifts), so
no step re-detects it; a file missing from it is an error.

An existing config is only rewritten for a stem in --rewrite (default: every
stem), and a missing one is always written. A box passes its own sweep datasets
there, so --bias-precision / --bias-patience reach those and do not move
another dataset's settings, which name the directories its 03.0 models are in.
A rewrite keeps the file's fold_bias_suffix, the per-fold picks a person
copied in after 03.1.

    python workflows/dcai/make_configs.py \\
        --fragments-dir /dcai/projects/iu_0109/datasets/amsc/fragments \\
        --dataset-root  /dcai/projects/iu_0109/datasets/amsc \\
        --shifts        /dcai/projects/iu_0109/datasets/amsc/chrombpnet/shifts.json

Stdlib only: it runs before any environment is active, like utils/config.py.
"""

import argparse
import json
import re
import sys
from pathlib import Path

SUFFIX = ".fragments.tsv.gz"

TEMPLATE = """\
# Generated by workflows/dcai/make_configs.py -- edit that, not this file.
# One ChromBPNet dataset per 10x library; see workflows/dcai/README.md.
dataset_name: {name}
assay: ATAC

# 10x cellranger-arc fragments (BGZF). Every barcode is kept.
signal_path: "{fragments}"
# Tn5 shift PRESENT in the fragments, detected by workflows/dcai/detect_shifts.py
# (scPrinter's detector and chrombpnet's agreeing); 00.0 and 00.0.call_peaks
# correct it to chrombpnet's +4/-4.
plus_shift: {plus_shift}
minus_shift: {minus_shift}

# 00.0.prepare_signal: figwig counts the same cuts on several cores. It writes
# no filtered fragments, so filter_main_chroms is off.
bigwig_engine: figwig
filter_main_chroms: false

# 00.0.call_peaks writes `regions` (igvf_pseudobulking_pipeline recipe, MACS3 PR #756).
call_peaks: true
macs_input: bed
regions: "{regions}"
# 00.1: one 1000-bp window per MACS summit row.
peak_summit_window: 1000

output_dir: "{output_dir}"
peak_type: all
folds: ["0", "1", "2", "3", "4"]

bias_factors: ["0.5", "0.6", "0.7", "0.8"]
bias_suffixes_sweep: ["_05", "_06", "_07", "_08"]
{bias_precision_line}{bias_patience_line}
# Filled in by hand after 03.1 writes selected_bias_per_fold.tsv.
fold_bias_suffix:
{fold_bias_suffix}"""

FOLDS = ["0", "1", "2", "3", "4"]


def existing_fold_bias_suffix(path: Path) -> dict:
    """The fold_bias_suffix entries an existing config has, or {}."""
    if not path.exists():
        return {}
    block = re.search(r"^fold_bias_suffix:\n((?:[ \t]+.*\n?)*)", path.read_text(), re.M)
    if not block:
        return {}
    return dict(re.findall(r'^[ \t]+"(\d+)":[ \t]*"([^"]*)"', block.group(1), re.M))


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--fragments-dir", required=True, type=Path)
    ap.add_argument("--dataset-root", required=True, type=Path)
    ap.add_argument("--shifts", required=True, type=Path, help="detect_shifts.py output")
    ap.add_argument("--configs-dir", type=Path, default=None,
                    help="default: <dataset-root>/chrombpnet/configs")  # fmt: skip
    ap.add_argument("--prefix", default="amsc_", help="dataset name prefix")
    ap.add_argument(
        "--bias-patience",
        default="",
        help="bias_patience for the 03.0 sweep (early-stopping patience); empty = chrombpnet's 5",
    )
    ap.add_argument(
        "--bias-precision",
        default="",
        help="bias_precision for the 03.0 sweep (bf16, highest); empty = chrombpnet's default",
    )
    ap.add_argument(
        "--rewrite",
        default=None,
        help="space-separated stems whose existing configs are rewritten; others are only "
        "written when missing (default: rewrite all)",
    )
    args = ap.parse_args(argv)
    rewrite = None if args.rewrite is None else set(args.rewrite.split())

    shifts = json.loads(args.shifts.read_text())
    configs_dir = args.configs_dir or args.dataset_root / "chrombpnet" / "configs"
    files = sorted(args.fragments_dir.glob(f"*{SUFFIX}"))
    if not files:
        print(f"ERROR: no *{SUFFIX} under {args.fragments_dir}", file=sys.stderr)
        return 1
    missing = [f.name for f in files if f.name[: -len(SUFFIX)] not in shifts]
    if missing:
        print(f"ERROR: no detected shift for: {', '.join(missing)}", file=sys.stderr)
        return 1

    for f in files:
        stem = f.name[: -len(SUFFIX)]
        name = f"{args.prefix}{stem}"
        rec = shifts[stem]
        out = configs_dir / name / "config.yaml"
        if out.exists() and rewrite is not None and stem not in rewrite:
            print(out)
            continue
        picks = existing_fold_bias_suffix(out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(
            TEMPLATE.format(
                name=name,
                fragments=f.resolve(),
                plus_shift=int(rec["plus_shift"]),
                minus_shift=int(rec["minus_shift"]),
                regions=args.dataset_root / "peaks" / name / f"{name}.narrowPeak.gz",
                output_dir=args.dataset_root / "chrombpnet" / name,
                bias_patience_line=(
                    "# 03.0 sweep models stop after this many epochs without improvement (own _p<N> dirs).\n"
                    f"bias_patience: {args.bias_patience}\n"
                    if args.bias_patience
                    else ""
                ),
                bias_precision_line=(
                    "# 03.0 sweep models in bf16 (own bias_model_<f>_bf16/ dirs); 04.0 stays full precision.\n"
                    f"bias_precision: {args.bias_precision}\n"
                    if args.bias_precision
                    else ""
                ),
                fold_bias_suffix="".join(f'  "{f}": "{picks.get(f, "")}"\n' for f in FOLDS),
            )
        )
        print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
